name: Create GitHub Release

on:
    push:
        tags:
            - 'v*'
permissions: write-all
jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                generate_release_notes: true
                files: |
                  docs/tasks.postman_collection.json
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}